#!/bin/bash
# ─── SPIR-V Shader Build Pipeline ─────────────────────────────────────────────
# Compiles GLSL shaders to SPIR-V binary for use in Vulkan pipeline.
# Requires: glslangValidator (included in Android SDK or Vulkan SDK)
#
# Usage: ./build_shaders.sh [path_to_glslangValidator]
#
# This script:
# 1. Compiles ps2.vert + ps2.frag → ps2.spv (SPIR-V binary)
# 2. Converts SPIR-V to C header arrays (ps2_shaders.h) for embedding
# 3. The generated header is included by gs_vulkan.cpp

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
VERT_SRC="${SCRIPT_DIR}/gs/shaders/ps2.vert"
FRAG_SRC="${SCRIPT_DIR}/gs/shaders/ps2.frag"
OUT_DIR="${SCRIPT_DIR}/gs/shaders"
SPV_VERT="${OUT_DIR}/ps2.vert.spv"
SPV_FRAG="${OUT_DIR}/ps2.frag.spv"
HEADER="${OUT_DIR}/ps2_shaders.h"

# Find glslangValidator
GLSLANG="${1:-glslangValidator}"
if ! command -v "$GLSLANG" &>/dev/null; then
    # Try Android SDK path
    for sdk_dir in "$ANDROID_HOME" "$ANDROID_SDK_ROOT" "/opt/android-sdk"; do
        for ver in "$(ls "$sdk_dir"/shader-tools/ 2>/dev/null | sort -V | tail -1)" "latest"; do
            if [ -f "$sdk_dir/shader-tools/$ver/glslangValidator" ]; then
                GLSLANG="$sdk_dir/shader-tools/$ver/glslangValidator"
                break 2
            fi
        done
    done
fi

if ! command -v "$GLSLANG" &>/dev/null; then
    echo "ERROR: glslangValidator not found. Install Vulkan SDK or pass path as argument."
    echo "  Ubuntu: sudo apt install glslang-tools"
    echo "  Android: \$ANDROID_HOME/shader-tools/<version>/glslangValidator"
    exit 1
fi

echo "Using glslangValidator: $GLSLANG"
echo "Compiling shaders..."

# Step 1: Compile to SPIR-V
"$GLSLANG" -V "$VERT_SRC" -o "$SPV_VERT" --target-env vulkan1.0
echo "  Compiled $VERT_SRC -> $SPV_VERT"

"$GLSLANG" -V "$FRAG_SRC" -o "$SPV_FRAG" --target-env vulkan1.0
echo "  Compiled $FRAG_SRC -> $SPV_FRAG"

# Step 2: Generate C header
echo "Generating $HEADER..."

cat > "$HEADER" << 'EOF'
// Auto-generated by build_shaders.sh — DO NOT EDIT
// Contains compiled SPIR-V shaders as C arrays
#pragma once
#include <cstdint>
#include <cstddef>

EOF

# Convert each SPIR-V binary to a uint32_t array
for spv in "$SPV_VERT" "$SPV_FRAG"; do
    name=$(basename "$spv" .spv)
    varname="${name}_spv"
    num_words=$(($(wc -c < "$spv") / 4))
    
    echo "static const uint32_t ${varname}[] = {" >> "$HEADER"
    
    # xxd -p gives hex, process to 0xNNNNNNNN format
    xxd -p -l $(($(wc -c < "$spv") / 4 * 4)) "$spv" | tr -d '\n' | sed 's/\(..\)\(..\)\(..\)\(..\)/0x\4\3\2\1,/g' >> "$HEADER"
    
    echo "};" >> "$HEADER"
    echo "static constexpr size_t ${varname}_size = sizeof(${varname});" >> "$HEADER"
    echo "" >> "$HEADER"
    echo "  ${varname}: ${num_words} words ($(( $(wc -c < "$spv") )) bytes)"
done

echo ""
echo "Done! Generated: $HEADER"
echo "Include this in gs_vulkan.cpp to use pre-compiled SPIR-V shaders."
