#include "hw_module_gen.h"
#include <android/log.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <fstream>
#include <sstream>
#include <cstring>

#define LOG_TAG "HWModuleGen"
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)

static void ensure_parent_dirs(const std::string& path) {
    size_t pos = 0;
    while ((pos = path.find('/', pos + 1)) != std::string::npos) {
        mkdir(path.substr(0, pos).c_str(), 0755);
    }
}

void HW_ModuleGen::write_file(const std::string& path, const std::string& content) {
    ensure_parent_dirs(path);
    std::ofstream ofs(path, std::ios::binary);
    if (!ofs.is_open()) {
        LOGE("Failed to open file for writing: %s", path.c_str());
        return;
    }
    ofs.write(content.data(), content.size());
    ofs.close();
    LOGI("Wrote %zu bytes to %s", content.size(), path.c_str());
}

void HW_ModuleGen::generate_all(const ELF_Analyzer& analyzer, const std::string& out_dir) {
    LOGI("Generating all HW modules to %s", out_dir.c_str());
    mkdir(out_dir.c_str(), 0755);

    auto ee = generate_ee_module(analyzer);
    write_file(out_dir + "/ee_state.h", ee.header_code);
    write_file(out_dir + "/ee_state.cpp", ee.source_code);

    auto iop = generate_iop_module(analyzer);
    write_file(out_dir + "/iop_state.h", iop.header_code);
    write_file(out_dir + "/iop_state.cpp", iop.source_code);

    auto gs = generate_gs_module(analyzer);
    write_file(out_dir + "/gs_renderer.h", gs.header_code);
    write_file(out_dir + "/gs_renderer.cpp", gs.source_code);

    auto dma = generate_dma_module(analyzer);
    write_file(out_dir + "/dma_controller.h", dma.header_code);
    write_file(out_dir + "/dma_controller.cpp", dma.source_code);

    auto vu = generate_vu_module(analyzer);
    write_file(out_dir + "/vu_processor.h", vu.header_code);
    write_file(out_dir + "/vu_processor.cpp", vu.source_code);

    LOGI("All HW modules generated successfully");
}

// ============================================================================
// EE Module
// ============================================================================

HWModule HW_ModuleGen::generate_ee_module(const ELF_Analyzer& analyzer) {
    HWModule mod;
    mod.name = "ee";
    mod.header_code = generate_ee_header(analyzer);
    mod.source_code = generate_ee_source(analyzer);
    return mod;
}

std::string HW_ModuleGen::generate_ee_header(const ELF_Analyzer& analyzer) {
    std::ostringstream os;

    os << "#pragma once\n";
    os << "#include <cstdint>\n";
    os << "#include <cstring>\n";
    os << "#include <array>\n";
    os << "\n";
    os << "// EE hardware state - self-contained, no emulator dependencies\n";
    os << "// Generated by HW_ModuleGen for PS2-Recompiler AOT pipeline\n";
    os << "\n";
    os << "static constexpr size_t EE_RAM_SIZE      = 32 * 1024 * 1024;\n";
    os << "static constexpr size_t EE_SCRATCH_SIZE   = 16 * 1024;\n";
    os << "static constexpr size_t EE_BIOS_SIZE      = 4 * 1024 * 1024;\n";
    os << "static constexpr size_t EE_KERNEL_BASE    = 0x80000000;\n";
    os << "static constexpr size_t EE_RAM_BASE       = 0x00000000;\n";
    os << "static constexpr size_t EE_SCRATCH_BASE   = 0x70000000;\n";
    os << "static constexpr size_t EE_BIOS_BASE      = 0x1FC00000;\n";
    os << "static constexpr int    EE_GPR_COUNT      = 32;\n";
    os << "static constexpr int    EE_FPU_REG_COUNT  = 32;\n";
    os << "\n";
    os << "static constexpr uint32_t EE_EXC_TLB_REFILL      = 0x80000000;\n";
    os << "static constexpr uint32_t EE_EXC_COUNTER         = 0x80000080;\n";
    os << "static constexpr uint32_t EE_EXC_DEBUG           = 0x80000040;\n";
    os << "static constexpr uint32_t EE_EXC_COMMON          = 0x80000100;\n";
    os << "static constexpr uint32_t EE_EXC_INTERRUPT       = 0x80000200;\n";
    os << "static constexpr uint32_t EE_EXC_SYSCALL         = 0x80000280;\n";
    os << "static constexpr uint32_t EE_EXC_ADDR_ERROR      = 0x80000180;\n";
    os << "static constexpr uint32_t EE_EXC_ARITH_OVERFLOW  = 0x80000140;\n";
    os << "static constexpr uint32_t EE_EXC_UNIMPLEMENTED   = 0x80000180;\n";
    os << "\n";
    os << "enum COP0_Reg : int {\n";
    os << "    COP0_Index      = 0, COP0_Random     = 1,\n";
    os << "    COP0_EntryLo0   = 2, COP0_EntryLo1   = 3,\n";
    os << "    COP0_Context    = 4, COP0_PageMask   = 5,\n";
    os << "    COP0_Wired      = 6, COP0_BadVAddr   = 8,\n";
    os << "    COP0_Count      = 9, COP0_EntryHi    = 10,\n";
    os << "    COP0_Compare    = 11, COP0_Status    = 12,\n";
    os << "    COP0_Cause      = 13, COP0_EPC       = 14,\n";
    os << "    COP0_PRId       = 15, COP0_Config    = 16,\n";
    os << "    COP0_LLAddr     = 17, COP0_WatchLo   = 18,\n";
    os << "    COP0_WatchHi    = 19, COP0_TagLo     = 28,\n";
    os << "    COP0_TagHi      = 29, COP0_ErrorEPC  = 30,\n";
    os << "    COP0_COUNT_MAX  = 32\n";
    os << "};\n";
    os << "\n";
    os << "enum FPU_Flag : uint32_t {\n";
    os << "    FPU_FS=1u<<24, FPU_FO=1u<<23, FPU_FU=1u<<22, FPU_FI=1u<<21,\n";
    os << "    FPU_FV=1u<<14, FPU_FZI=1u<<12, FPU_FUF=1u<<11,\n";
    os << "    FPU_FOF=1u<<10, FPU_FX=1u<<9, FPU_FIS=1u<<8\n";
    os << "};\n";
    os << "\n";
    os << "enum EE_IntMask : uint16_t {\n";
    os << "    EE_INT_VB=1<<0, EE_INT_VBLANK=1<<1, EE_INT_GPU=1<<2,\n";
    os << "    EE_INT_SIF0=1<<3, EE_INT_SIF1=1<<4, EE_INT_SIF2=1<<5,\n";
    os << "    EE_INT_VIF0=1<<6, EE_INT_VIF1=1<<7, EE_INT_VU0=1<<8,\n";
    os << "    EE_INT_VU0_DMA=1<<9, EE_INT_VU1=1<<10, EE_INT_VU1_DMA=1<<11,\n";
    os << "    EE_INT_IPU=1<<12, EE_INT_A_RSV=1<<13,\n";
    os << "    EE_INT_O_L32K=1<<14, EE_INT_O_32L16K=1<<15\n";
    os << "};\n";
    os << "\n";
    os << "struct EE_GPR {\n";
    os << "    uint64_t r[EE_GPR_COUNT];\n";
    os << "    uint64_t lo;\n";
    os << "    uint64_t hi;\n";
    os << "    void reset() { memset(r, 0, sizeof(r)); lo = 0; hi = 0; }\n";
    os << "    void write(int reg, uint64_t val) {\n";
    os << "        if (reg > 0 && reg < EE_GPR_COUNT) r[reg] = val;\n";
    os << "    }\n";
    os << "    uint64_t read(int reg) const {\n";
    os << "        return (reg > 0 && reg < EE_GPR_COUNT) ? r[reg] : 0;\n";
    os << "    }\n";
    os << "};\n";
    os << "\n";
    os << "struct EE_FPU {\n";
    os << "    uint32_t regs[EE_FPU_REG_COUNT];\n";
    os << "    uint32_t fcsr;\n";
    os << "    uint32_t fpu_impl;\n";
    os << "    void reset() { memset(regs, 0, sizeof(regs)); fcsr = 0; fpu_impl = 0; }\n";
    os << "};\n";
    os << "\n";
    os << "struct EE_State {\n";
    os << "    EE_GPR gpr;\n";
    os << "    uint64_t pc;\n";
    os << "    uint64_t npc;\n";
    os << "    bool branch_delay;\n";
    os << "    bool branch_delay_slot;\n";
    os << "    uint64_t branch_target;\n";
    os << "    uint32_t cop0[COP0_COUNT_MAX];\n";
    os << "    EE_FPU fpu;\n";
    os << "    bool halted;\n";
    os << "    bool exception_pending;\n";
    os << "    uint16_t intc_stat;\n";
    os << "    uint16_t intc_mask;\n";
    os << "    uint32_t dmac_stat;\n";
    os << "    uint32_t dmac_mask;\n";
    os << "    uint32_t timer_count;\n";
    os << "    uint32_t timer_target;\n";
    os << "    uint8_t ram[EE_RAM_SIZE];\n";
    os << "    uint8_t scratchpad[EE_SCRATCH_SIZE];\n";
    os << "    uint8_t bios[EE_BIOS_SIZE];\n";
    os << "    bool cache_isolated;\n";
    os << "    bool cache_swapped;\n";
    os << "    uint64_t cycle_count;\n";
    os << "    uint64_t instruction_count;\n";
    os << "    void reset();\n";
    os << "    uint8_t*  phys_ptr(uint32_t addr);\n";
    os << "    uint32_t  mem_read32(uint32_t addr);\n";
    os << "    uint64_t  mem_read64(uint32_t addr);\n";
    os << "    void      mem_write32(uint32_t addr, uint32_t val);\n";
    os << "    void      mem_write64(uint32_t addr, uint64_t val);\n";
    os << "    void      intc_update();\n";
    os << "    void      intc_assert(uint16_t cause);\n";
    os << "    bool      has_pending_interrupt() const;\n";
    os << "    void      trigger_exception(uint32_t vector, int cause_code, int excode);\n";
    os << "    void      return_from_exception();\n";
    os << "    uint32_t  kernel_entry_point() const;\n";
    os << "    void      load_bios_kernel_vectors();\n";
    os << "};\n";

    return os.str();
}

std::string HW_ModuleGen::generate_ee_source(const ELF_Analyzer& analyzer) {
    std::ostringstream os;

    os << "#include \"ee_state.h\"\n";
    os << "#include <android/log.h>\n";
    os << "#include <cstring>\n";
    os << "#include <cstdio>\n";
    os << "\n";
    os << "#define LOG_TAG \"EE\"\n";
    os << "#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)\n";
    os << "#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)\n";
    os << "#define LOGW(...) __android_log_print(ANDROID_LOG_WARN, LOG_TAG, __VA_ARGS__)\n";
    os << "\n";

    os << "void EE_State::reset() {\n";
    os << "    gpr.reset();\n";
    os << "    pc = 0xBFC00000;\n";
    os << "    npc = pc + 4;\n";
    os << "    branch_delay = false;\n";
    os << "    branch_delay_slot = false;\n";
    os << "    branch_target = 0;\n";
    os << "    fpu.reset();\n";
    os << "    memset(cop0, 0, sizeof(cop0));\n";
    os << "    halted = false;\n";
    os << "    exception_pending = false;\n";
    os << "    intc_stat = 0;\n";
    os << "    intc_mask = 0;\n";
    os << "    dmac_stat = 0;\n";
    os << "    dmac_mask = 0;\n";
    os << "    timer_count = 0;\n";
    os << "    timer_target = 0;\n";
    os << "    memset(ram, 0, sizeof(ram));\n";
    os << "    memset(scratchpad, 0, sizeof(scratchpad));\n";
    os << "    memset(bios, 0xFF, sizeof(bios));\n";
    os << "    cache_isolated = false;\n";
    os << "    cache_swapped = false;\n";
    os << "    cycle_count = 0;\n";
    os << "    instruction_count = 0;\n";
    os << "    cop0[COP0_Status] = 0x10000;\n";
    os << "    cop0[COP0_PRId]   = 0x00002E10;\n";
    os << "    cop0[COP0_Config] = 0x17;\n";
    os << "    cop0[COP0_Random] = 0x3F;\n";
    os << "    cop0[COP0_Wired]  = 0;\n";
    os << "    cop0[COP0_Count]  = 0;\n";
    os << "    cop0[COP0_Compare]= 0;\n";
    os << "    LOGI(\"EE reset: PC=0x%08X\", (uint32_t)pc);\n";
    os << "}\n";
    os << "\n";

    os << "uint8_t* EE_State::phys_ptr(uint32_t addr) {\n";
    os << "    addr &= 0x1FFFFFFF;\n";
    os << "    if (addr < EE_RAM_SIZE) return &ram[addr];\n";
    os << "    if (addr >= EE_SCRATCH_BASE && addr < EE_SCRATCH_BASE + EE_SCRATCH_SIZE)\n";
    os << "        return &scratchpad[addr - EE_SCRATCH_BASE];\n";
    os << "    if (addr >= 0x1FC00000 && addr < 0x1FC00000 + EE_BIOS_SIZE)\n";
    os << "        return &bios[addr - 0x1FC00000];\n";
    os << "    if (addr >= 0x80000000 && addr < 0x80000000 + EE_RAM_SIZE)\n";
    os << "        return &ram[addr - 0x80000000];\n";
    os << "    LOGW(\"EE phys_ptr: unmapped 0x%08X\", addr);\n";
    os << "    return nullptr;\n";
    os << "}\n";
    os << "\n";

    os << "uint32_t EE_State::mem_read32(uint32_t addr) {\n";
    os << "    uint8_t* ptr = phys_ptr(addr);\n";
    os << "    if (!ptr) { LOGE(\"EE read32: unmapped 0x%08X\", addr); return 0; }\n";
    os << "    uint32_t val; memcpy(&val, ptr, 4); return val;\n";
    os << "}\n";
    os << "\n";
    os << "uint64_t EE_State::mem_read64(uint32_t addr) {\n";
    os << "    uint8_t* ptr = phys_ptr(addr);\n";
    os << "    if (!ptr) { LOGE(\"EE read64: unmapped 0x%08X\", addr); return 0; }\n";
    os << "    uint64_t val; memcpy(&val, ptr, 8); return val;\n";
    os << "}\n";
    os << "\n";

    os << "void EE_State::mem_write32(uint32_t addr, uint32_t val) {\n";
    os << "    uint8_t* ptr = phys_ptr(addr);\n";
    os << "    if (!ptr) { LOGE(\"EE write32: unmapped 0x%08X\", addr); return; }\n";
    os << "    memcpy(ptr, &val, 4);\n";
    os << "}\n";
    os << "\n";
    os << "void EE_State::mem_write64(uint32_t addr, uint64_t val) {\n";
    os << "    uint8_t* ptr = phys_ptr(addr);\n";
    os << "    if (!ptr) { LOGE(\"EE write64: unmapped 0x%08X\", addr); return; }\n";
    os << "    memcpy(ptr, &val, 8);\n";
    os << "}\n";
    os << "\n";

    os << "void EE_State::intc_update() {\n";
    os << "    uint16_t pending = intc_stat & intc_mask;\n";
    os << "    if (pending) { cop0[COP0_Cause] |= (1u << 10); exception_pending = true; }\n";
    os << "    else { cop0[COP0_Cause] &= ~(1u << 10); exception_pending = false; }\n";
    os << "    uint32_t dma_pending = dmac_stat & dmac_mask;\n";
    os << "    if (dma_pending) { cop0[COP0_Cause] |= (1u << 10); exception_pending = true; }\n";
    os << "}\n";
    os << "\n";
    os << "void EE_State::intc_assert(uint16_t cause) {\n";
    os << "    intc_stat |= cause;\n";
    os << "    intc_update();\n";
    os << "}\n";
    os << "\n";
    os << "bool EE_State::has_pending_interrupt() const {\n";
    os << "    if (!(cop0[COP0_Status] & (1u << 16))) return false;\n";
    os << "    uint8_t im = (cop0[COP0_Status] >> 8) & 0xFF;\n";
    os << "    uint8_t ip = (cop0[COP0_Cause] >> 8) & 0xFF;\n";
    os << "    return (im & ip) != 0;\n";
    os << "}\n";
    os << "\n";

    os << "void EE_State::trigger_exception(uint32_t vector, int cause_code, int excode) {\n";
    os << "    uint32_t status = cop0[COP0_Status];\n";
    os << "    uint32_t cause  = cop0[COP0_Cause];\n";
    os << "    uint32_t epc    = (uint32_t)pc;\n";
    os << "    cause &= ~0x7C;\n";
    os << "    cause |= (excode & 0x1F) << 2;\n";
    os << "    if (branch_delay_slot) { epc -= 4; cause |= (1u << 31); }\n";
    os << "    else { cause &= ~(1u << 31); }\n";
    os << "    status |= (1u << 1);\n";
    os << "    cop0[COP0_Cause]  = cause;\n";
    os << "    cop0[COP0_EPC]    = epc;\n";
    os << "    cop0[COP0_Status] = status;\n";
    os << "    pc = vector;\n";
    os << "    npc = vector + 4;\n";
    os << "    branch_delay_slot = false;\n";
    os << "    LOGI(\"EE exception: vector=0x%08X cause=%d EPC=0x%08X\", vector, cause_code, epc);\n";
    os << "}\n";
    os << "\n";
    os << "void EE_State::return_from_exception() {\n";
    os << "    cop0[COP0_Status] &= ~(1u << 1);\n";
    os << "    pc = cop0[COP0_EPC];\n";
    os << "    npc = pc + 4;\n";
    os << "    branch_delay_slot = false;\n";
    os << "    LOGI(\"EE return from exception: PC=0x%08X\", (uint32_t)pc);\n";
    os << "}\n";
    os << "\n";

    os << "uint32_t EE_State::kernel_entry_point() const {\n";
    os << "    return 0x00100000;\n";
    os << "}\n";
    os << "\n";
    os << "void EE_State::load_bios_kernel_vectors() {\n";
    os << "    LOGI(\"EE: BIOS kernel vectors loaded (PC=0x%08X)\", (uint32_t)pc);\n";
    os << "    LOGI(\"  TLB Refill = 0x%08X\", EE_EXC_TLB_REFILL);\n";
    os << "    LOGI(\"  Interrupt  = 0x%08X\", EE_EXC_INTERRUPT);\n";
    os << "    LOGI(\"  Syscall    = 0x%08X\", EE_EXC_SYSCALL);\n";
    os << "    if (pc < 0xBFC00000 || pc >= 0xBFC00000 + EE_BIOS_SIZE) {\n";
    os << "        pc = 0xBFC00000;\n";
    os << "        npc = pc + 4;\n";
    os << "    }\n";
    os << "    if (bios[0] != 0xFF)\n";
    os << "        LOGI(\"BIOS ROM loaded (first byte: 0x%02X)\", bios[0]);\n";
    os << "    else\n";
    os << "        LOGW(\"BIOS ROM empty - load BIOS file externally\");\n";
    os << "    LOGI(\"EE: Entry point set to 0x%08X\", (uint32_t)pc);\n";
    os << "}\n";

    return os.str();
}

// ============================================================================
// IOP Module
// ============================================================================

HWModule HW_ModuleGen::generate_iop_module(const ELF_Analyzer& analyzer) {
    HWModule mod;
    mod.name = "iop";
    mod.header_code = generate_iop_header();
    mod.source_code = generate_iop_source();
    return mod;
}

std::string HW_ModuleGen::generate_iop_header() {
    std::ostringstream os;

    os << "#pragma once\n";
    os << "#include <cstdint>\n";
    os << "#include <cstring>\n";
    os << "#include <array>\n";
    os << "\n";
    os << "// IOP hardware state - self-contained, no emulator dependencies\n";
    os << "// Generated by HW_ModuleGen for PS2-Recompiler AOT pipeline\n";
    os << "\n";
    os << "static constexpr size_t IOP_RAM_SIZE  = 2 * 1024 * 1024;\n";
    os << "static constexpr size_t IOP_RAM_BASE  = 0x00000000;\n";
    os << "static constexpr int    IOP_GPR_COUNT = 32;\n";
    os << "\n";

    os << "struct IOP_GPR {\n";
    os << "    uint32_t r[IOP_GPR_COUNT];\n";
    os << "    void reset() { memset(r, 0, sizeof(r)); }\n";
    os << "    void write(int reg, uint32_t val) {\n";
    os << "        if (reg > 0 && reg < IOP_GPR_COUNT) r[reg] = val;\n";
    os << "    }\n";
    os << "    uint32_t read(int reg) const {\n";
    os << "        return (reg > 0 && reg < IOP_GPR_COUNT) ? r[reg] : 0;\n";
    os << "    }\n";
    os << "};\n";
    os << "\n";

    os << "struct IOP_INTC {\n";
    os << "    uint32_t stat;\n";
    os << "    uint32_t mask;\n";
    os << "    void reset() { stat = 0; mask = 0; }\n";
    os << "    void write_stat(uint32_t val) { stat &= val; }\n";
    os << "    void write_mask(uint32_t val) { mask = val; }\n";
    os << "    bool has_interrupt() const { return (stat & mask) != 0; }\n";
    os << "    void assert_irq(uint32_t cause) { stat |= cause; }\n";
    os << "    void clear_irq(uint32_t cause)  { stat &= ~cause; }\n";
    os << "};\n";
    os << "\n";

    os << "struct IOP_DMAC {\n";
    os << "    struct Channel { uint32_t base; uint32_t block_control; uint32_t ch_control; };\n";
    os << "    static constexpr int CHANNEL_COUNT = 16;\n";
    os << "    Channel channels[CHANNEL_COUNT];\n";
    os << "    uint32_t dpcr;\n";
    os << "    uint32_t dicr;\n";
    os << "    void reset() { memset(channels, 0, sizeof(channels)); dpcr = 0x07654321; dicr = 0; }\n";
    os << "    void write_ch_base(int ch, uint32_t val) {\n";
    os << "        if (ch < CHANNEL_COUNT) channels[ch].base = val;\n";
    os << "    }\n";
    os << "    void write_ch_block(int ch, uint32_t val) {\n";
    os << "        if (ch < CHANNEL_COUNT) channels[ch].block_control = val;\n";
    os << "    }\n";
    os << "    void write_ch_ctrl(int ch, uint32_t val) {\n";
    os << "        if (ch < CHANNEL_COUNT) channels[ch].ch_control = val;\n";
    os << "    }\n";
    os << "    void write_dpcr(uint32_t val) { dpcr = val; }\n";
    os << "    void write_dicr(uint32_t val) {\n";
    os << "        dicr = (dicr & ~0x7F000000) | (dicr & ~val & 0x7F000000);\n";
    os << "    }\n";
    os << "};\n";
    os << "\n";

    os << "struct IOP_SIF {\n";
    os << "    uint32_t smcom, mscom, smgs, mgs;\n";
    os << "    uint32_t sbus_ctl, sbus_sync, sbus_cvt;\n";
    os << "    uint32_t ifc, iff, sif0_msk;\n";
    os << "    void reset() {\n";
    os << "        smcom = 0; mscom = 0; smgs = 0; mgs = 0;\n";
    os << "        sbus_ctl = 0x1D9; sbus_sync = 0; sbus_cvt = 0;\n";
    os << "        ifc = 0; iff = 0; sif0_msk = 0;\n";
    os << "    }\n";
    os << "};\n";
    os << "\n";

    os << "struct IOP_State {\n";
    os << "    IOP_GPR gpr;\n";
    os << "    uint32_t pc, npc;\n";
    os << "    bool halted;\n";
    os << "    uint32_t cop0[32];\n";
    os << "    uint8_t ram[IOP_RAM_SIZE];\n";
    os << "    IOP_INTC intc;\n";
    os << "    IOP_DMAC dmac;\n";
    os << "    IOP_SIF  sif;\n";
    os << "    uint32_t timer_count[3], timer_target[3], timer_mode[3];\n";
    os << "    uint32_t sio2_fifo[32], sio2_recv[32], sio2_ctrl, sio2_stat;\n";
    os << "    uint64_t cycle_count;\n";
    os << "    void reset();\n";
    os << "    uint8_t*  phys_ptr(uint32_t addr);\n";
    os << "    uint8_t   mem_read8(uint32_t addr);\n";
    os << "    uint16_t  mem_read16(uint32_t addr);\n";
    os << "    uint32_t  mem_read32(uint32_t addr);\n";
    os << "    void      mem_write8(uint32_t addr, uint8_t val);\n";
    os << "    void      mem_write16(uint32_t addr, uint16_t val);\n";
    os << "    void      mem_write32(uint32_t addr, uint32_t val);\n";
    os << "    uint32_t  io_read32(uint32_t addr);\n";
    os << "    void      io_write32(uint32_t addr, uint32_t val);\n";
    os << "};\n";

    return os.str();
}

std::string HW_ModuleGen::generate_iop_source() {
    std::ostringstream os;

    os << "#include \"iop_state.h\"\n";
    os << "#include <android/log.h>\n";
    os << "#include <cstring>\n";
    os << "\n";
    os << "#define LOG_TAG \"IOP\"\n";
    os << "#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)\n";
    os << "#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)\n";
    os << "#define LOGW(...) __android_log_print(ANDROID_LOG_WARN, LOG_TAG, __VA_ARGS__)\n";
    os << "\n";

    os << "void IOP_State::reset() {\n";
    os << "    gpr.reset();\n";
    os << "    pc = 0xBFC00000;\n";
    os << "    npc = pc + 4;\n";
    os << "    halted = false;\n";
    os << "    memset(cop0, 0, sizeof(cop0));\n";
    os << "    memset(ram, 0, sizeof(ram));\n";
    os << "    intc.reset();\n";
    os << "    dmac.reset();\n";
    os << "    sif.reset();\n";
    os << "    memset(timer_count, 0, sizeof(timer_count));\n";
    os << "    memset(timer_target, 0, sizeof(timer_target));\n";
    os << "    memset(timer_mode, 0, sizeof(timer_mode));\n";
    os << "    memset(sio2_fifo, 0, sizeof(sio2_fifo));\n";
    os << "    memset(sio2_recv, 0, sizeof(sio2_recv));\n";
    os << "    sio2_ctrl = 0;\n";
    os << "    sio2_stat = 0;\n";
    os << "    cycle_count = 0;\n";
    os << "    cop0[12] = 0x10000;\n";
    os << "    cop0[15] = 0x00000002;\n";
    os << "    LOGI(\"IOP reset: PC=0x%08X\", pc);\n";
    os << "}\n";
    os << "\n";

    os << "uint8_t* IOP_State::phys_ptr(uint32_t addr) {\n";
    os << "    addr &= 0x1FFFFFFF;\n";
    os << "    if (addr < IOP_RAM_SIZE) return &ram[addr];\n";
    os << "    LOGW(\"IOP phys_ptr: unmapped 0x%08X\", addr);\n";
    os << "    return nullptr;\n";
    os << "}\n";
    os << "\n";

    os << "uint8_t IOP_State::mem_read8(uint32_t addr) {\n";
    os << "    uint8_t* ptr = phys_ptr(addr);\n";
    os << "    return ptr ? *ptr : 0;\n";
    os << "}\n";
    os << "uint16_t IOP_State::mem_read16(uint32_t addr) {\n";
    os << "    uint8_t* ptr = phys_ptr(addr);\n";
    os << "    if (!ptr) return 0;\n";
    os << "    uint16_t val; memcpy(&val, ptr, 2); return val;\n";
    os << "}\n";
    os << "uint32_t IOP_State::mem_read32(uint32_t addr) {\n";
    os << "    uint8_t* ptr = phys_ptr(addr);\n";
    os << "    if (!ptr) return 0;\n";
    os << "    uint32_t val; memcpy(&val, ptr, 4); return val;\n";
    os << "}\n";
    os << "void IOP_State::mem_write8(uint32_t addr, uint8_t val) {\n";
    os << "    uint8_t* ptr = phys_ptr(addr);\n";
    os << "    if (ptr) *ptr = val;\n";
    os << "}\n";
    os << "void IOP_State::mem_write16(uint32_t addr, uint16_t val) {\n";
    os << "    uint8_t* ptr = phys_ptr(addr);\n";
    os << "    if (ptr) memcpy(ptr, &val, 2);\n";
    os << "}\n";
    os << "void IOP_State::mem_write32(uint32_t addr, uint32_t val) {\n";
    os << "    uint8_t* ptr = phys_ptr(addr);\n";
    os << "    if (ptr) memcpy(ptr, &val, 4);\n";
    os << "}\n";
    os << "\n";

    os << "uint32_t IOP_State::io_read32(uint32_t addr) {\n";
    os << "    if (addr == 0x1F801070) return intc.stat;\n";
    os << "    if (addr == 0x1F801074) return intc.mask;\n";
    os << "    if (addr == 0x1F8010F0) return dmac.dpcr;\n";
    os << "    if (addr == 0x1F8010F4) return dmac.dicr;\n";
    os << "    if (addr >= 0x1F801080 && addr < 0x1F8010F0) {\n";
    os << "        int ch = (addr - 0x1F801080) / 0x10;\n";
    os << "        int off = (addr - 0x1F801080) % 0x10;\n";
    os << "        if (ch < IOP_DMAC::CHANNEL_COUNT) {\n";
    os << "            if (off == 0x0) return dmac.channels[ch].base;\n";
    os << "            if (off == 0x4) return dmac.channels[ch].block_control;\n";
    os << "            if (off == 0x8) return dmac.channels[ch].ch_control;\n";
    os << "        }\n";
    os << "        return 0;\n";
    os << "    }\n";
    os << "    if (addr == 0x1F8010C0) return sif.smcom;\n";
    os << "    if (addr == 0x1F8010C4) return sif.mscom;\n";
    os << "    if (addr == 0x1F8010C8) return sif.smgs;\n";
    os << "    if (addr == 0x1F8010CC) return sif.mgs;\n";
    os << "    if (addr == 0x1F8010D0) return sif.sbus_ctl;\n";
    os << "    if (addr == 0x1F8010D4) return sif.sbus_sync;\n";
    os << "    if (addr == 0x1F8010D8) return sif.sbus_cvt;\n";
    os << "    if (addr == 0x1F8010E0) return sif.ifc;\n";
    os << "    if (addr == 0x1F8010E4) return sif.iff;\n";
    os << "    if (addr == 0x1F8010E8) return sif.sif0_msk;\n";
    os << "    if (addr >= 0x1F801100 && addr < 0x1F801110) {\n";
    os << "        int t = (addr - 0x1F801100) / 4;\n";
    os << "        if (t < 3) return timer_count[t];\n";
    os << "    }\n";
    os << "    if (addr >= 0x1F801110 && addr < 0x1F801120) {\n";
    os << "        int t = (addr - 0x1F801110) / 4;\n";
    os << "        if (t < 3) return timer_target[t];\n";
    os << "    }\n";
    os << "    if (addr >= 0x1F801120 && addr < 0x1F801130) {\n";
    os << "        int t = (addr - 0x1F801120) / 4;\n";
    os << "        if (t < 3) return timer_mode[t];\n";
    os << "    }\n";
    os << "    if (addr == 0x1F801040) {\n";
    os << "        if (sio2_stat & 0x04) return sio2_fifo[0];\n";
    os << "        return 0;\n";
    os << "    }\n";
    os << "    if (addr == 0x1F801044) return sio2_stat;\n";
    os << "    if (addr == 0x1F801048) {\n";
    os << "        uint32_t val = sio2_recv[0];\n";
    os << "        memmove(sio2_recv, sio2_recv + 1, sizeof(sio2_recv) - 4);\n";
    os << "        return val;\n";
    os << "    }\n";
    os << "    LOGW(\"IOP io_read32: unmapped 0x%08X\", addr);\n";
    os << "    return 0;\n";
    os << "}\n";
    os << "\n";

    os << "void IOP_State::io_write32(uint32_t addr, uint32_t val) {\n";
    os << "    if (addr == 0x1F801070) { intc.write_stat(val); return; }\n";
    os << "    if (addr == 0x1F801074) { intc.write_mask(val); return; }\n";
    os << "    if (addr == 0x1F8010F0) { dmac.write_dpcr(val); return; }\n";
    os << "    if (addr == 0x1F8010F4) { dmac.write_dicr(val); return; }\n";
    os << "    if (addr >= 0x1F801080 && addr < 0x1F8010F0) {\n";
    os << "        int ch = (addr - 0x1F801080) / 0x10;\n";
    os << "        int off = (addr - 0x1F801080) % 0x10;\n";
    os << "        if (ch < IOP_DMAC::CHANNEL_COUNT) {\n";
    os << "            if (off == 0x0) dmac.write_ch_base(ch, val);\n";
    os << "            else if (off == 0x4) dmac.write_ch_block(ch, val);\n";
    os << "            else if (off == 0x8) dmac.write_ch_ctrl(ch, val);\n";
    os << "        }\n";
    os << "        return;\n";
    os << "    }\n";
    os << "    if (addr == 0x1F8010C0) { sif.smcom = val; return; }\n";
    os << "    if (addr == 0x1F8010C4) { sif.mscom = val; return; }\n";
    os << "    if (addr == 0x1F8010C8) { sif.smgs = val; return; }\n";
    os << "    if (addr == 0x1F8010CC) { sif.mgs = val; return; }\n";
    os << "    if (addr == 0x1F8010D0) { sif.sbus_ctl = val; return; }\n";
    os << "    if (addr == 0x1F8010D4) { sif.sbus_sync = val; return; }\n";
    os << "    if (addr == 0x1F8010D8) { sif.sbus_cvt = val; return; }\n";
    os << "    if (addr == 0x1F8010E0) { sif.ifc = val; return; }\n";
    os << "    if (addr == 0x1F8010E4) { sif.iff = val; return; }\n";
    os << "    if (addr == 0x1F8010E8) { sif.sif0_msk = val; return; }\n";
    os << "    if (addr >= 0x1F801100 && addr < 0x1F801110) {\n";
    os << "        int t = (addr - 0x1F801100) / 4;\n";
    os << "        if (t < 3) timer_count[t] = val;\n";
    os << "        return;\n";
    os << "    }\n";
    os << "    if (addr >= 0x1F801110 && addr < 0x1F801120) {\n";
    os << "        int t = (addr - 0x1F801110) / 4;\n";
    os << "        if (t < 3) timer_target[t] = val;\n";
    os << "        return;\n";
    os << "    }\n";
    os << "    if (addr >= 0x1F801120 && addr < 0x1F801130) {\n";
    os << "        int t = (addr - 0x1F801120) / 4;\n";
    os << "        if (t < 3) timer_mode[t] = val;\n";
    os << "        return;\n";
    os << "    }\n";
    os << "    if (addr == 0x1F801040) {\n";
    os << "        if (sio2_stat & 0x04) {\n";
    os << "            memmove(sio2_fifo + 1, sio2_fifo, sizeof(sio2_fifo) - 4);\n";
    os << "            sio2_fifo[0] = val;\n";
    os << "        }\n";
    os << "        return;\n";
    os << "    }\n";
    os << "    if (addr == 0x1F801044) { sio2_stat = val; return; }\n";
    os << "    LOGW(\"IOP io_write32: unmapped 0x%08X = 0x%08X\", addr, val);\n";
    os << "}\n";

    return os.str();
}

// ============================================================================
// GS Module
// ============================================================================

HWModule HW_ModuleGen::generate_gs_module(const ELF_Analyzer& analyzer) {
    HWModule mod;
    mod.name = "gs";
    mod.header_code = generate_gs_header();
    mod.source_code = generate_gs_source();
    return mod;
}

std::string HW_ModuleGen::generate_gs_header() {
    std::ostringstream os;

    os << "#pragma once\n";
    os << "#include <cstdint>\n";
    os << "#include <cstring>\n";
    os << "#include <vector>\n";
    os << "#include <array>\n";
    os << "\n";
    os << "// GS renderer - self-contained, no emulator dependencies\n";
    os << "// Generated by HW_ModuleGen for PS2-Recompiler AOT pipeline\n";
    os << "\n";
    os << "static constexpr size_t VRAM_SIZE = 4 * 1024 * 1024;\n";
    os << "\n";

    os << "enum GS_Reg : uint32_t {\n";
    os << "    GS_PMODE=0x0000, GS_SMODE1=0x0010, GS_SMODE2=0x0020,\n";
    os << "    GS_DISPFB1=0x0080, GS_DISPLAY1=0x0090,\n";
    os << "    GS_DISPFB2=0x00A0, GS_DISPLAY2=0x00B0,\n";
    os << "    GS_BGCOLOR=0x0800, GS_FRAME1=0x0810, GS_FRAME2=0x0820,\n";
    os << "    GS_ZBUF1=0x0830, GS_ZBUF2=0x0840,\n";
    os << "    GS_XYOFFSET1=0x0850, GS_XYOFFSET2=0x0860,\n";
    os << "    GS_PRMODECONT=0x0870, GS_PRMODE=0x08B0,\n";
    os << "    GS_TEXCLUT=0x08C0, GS_SCISSOR1=0x08D0, GS_SCISSOR2=0x08E0,\n";
    os << "    GS_ALPHA=0x08F0, GS_DTHE=0x0920, GS_COLCLAMP=0x0930,\n";
    os << "    GS_FBA1=0x09A0, GS_FBA2=0x09B0,\n";
    os << "    GS_TRXDIR=0x09E0, GS_TRXPOS=0x09F0, GS_TRXREG=0x0A00, GS_TRXKICK=0x0A10,\n";
    os << "    GS_TEX0_1=0x0A40, GS_TEX0_2=0x0A60,\n";
    os << "    GS_TEX1_1=0x1A40, GS_TEX1_2=0x1A60,\n";
    os << "    GS_TEXA=0x1B00, GS_FOGCOL=0x1BD0, GS_TEXFLUSH=0x1C00\n";
    os << "};\n";
    os << "\n";

    os << "struct GIF_Tag {\n";
    os << "    uint32_t nloop:15; uint32_t eop:1; uint32_t pre:1;\n";
    os << "    uint32_t prim:11; uint32_t flg:2; uint32_t nreg:4;\n";
    os << "    uint32_t regs[4];\n";
    os << "};\n";
    os << "\n";

    os << "struct GS_Texture {\n";
    os << "    uint32_t tbp0, tbw, psm, tw, th, tcc, tfx, csm, cpsm, cld;\n";
    os << "    void reset() { memset(this, 0, sizeof(*this)); }\n";
    os << "};\n";
    os << "\n";

    os << "struct GS_FrameBuf {\n";
    os << "    uint32_t fbw, psm, fbp;\n";
    os << "    void reset() { fbw = 0; psm = 0; fbp = 0; }\n";
    os << "};\n";
    os << "\n";

    os << "struct GS_State {\n";
    os << "    uint8_t vram[VRAM_SIZE];\n";
    os << "    uint32_t pmode;\n";
    os << "    GS_FrameBuf dispfb[2], frame[2];\n";
    os << "    uint32_t zbuf[2];\n";
    os << "    int32_t xyoffset[2][2];\n";
    os << "    uint32_t scissor[2][4];\n";
    os << "    GS_Texture tex[2];\n";
    os << "    uint32_t texa, texclut;\n";
    os << "    uint32_t alpha, prmode, prmodecont, colclamp, dthe, fogcol;\n";
    os << "    uint32_t fba[2];\n";
    os << "    uint32_t trxdir, trxpos[6], trxreg[4], bgcol;\n";
    os << "    bool gif_active;\n";
    os << "    uint64_t frame_count;\n";
    os << "    void reset();\n";
    os << "    void write_priv(uint32_t addr, uint64_t val);\n";
    os << "    uint64_t read_priv(uint32_t addr);\n";
    os << "    void gif_transfer_tag(uint64_t tag_lo, uint64_t tag_hi);\n";
    os << "    void gif_transfer_data(const uint64_t* data, int count);\n";
    os << "    void upload_texture(uint32_t sbp, uint32_t sbw, uint32_t spsm,\n";
    os << "        uint32_t dbp, uint32_t dbw, uint32_t dpsm,\n";
    os << "        uint32_t src_x, uint32_t src_y, uint32_t dst_x, uint32_t dst_y,\n";
    os << "        uint32_t width, uint32_t height);\n";
    os << "};\n";

    return os.str();
}

std::string HW_ModuleGen::generate_gs_source() {
    std::ostringstream os;

    os << "#include \"gs_renderer.h\"\n";
    os << "#include <android/log.h>\n";
    os << "#include <cstring>\n";
    os << "\n";
    os << "#define LOG_TAG \"GS\"\n";
    os << "#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)\n";
    os << "#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)\n";
    os << "#define LOGW(...) __android_log_print(ANDROID_LOG_WARN, LOG_TAG, __VA_ARGS__)\n";
    os << "\n";

    os << "void GS_State::reset() {\n";
    os << "    memset(vram, 0, sizeof(vram));\n";
    os << "    pmode = 0;\n";
    os << "    for (int i = 0; i < 2; i++) {\n";
    os << "        dispfb[i].reset(); frame[i].reset();\n";
    os << "        zbuf[i] = 0;\n";
    os << "        xyoffset[i][0] = 0; xyoffset[i][1] = 0;\n";
    os << "        scissor[i][0] = 0; scissor[i][1] = 0;\n";
    os << "        scissor[i][2] = 0x1FFF; scissor[i][3] = 0x1FFF;\n";
    os << "        tex[i].reset(); fba[i] = 0;\n";
    os << "    }\n";
    os << "    texa = 0; texclut = 0; alpha = 0;\n";
    os << "    prmode = 0; prmodecont = 0; colclamp = 0;\n";
    os << "    dthe = 0; fogcol = 0; trxdir = 4;\n";
    os << "    memset(trxpos, 0, sizeof(trxpos));\n";
    os << "    memset(trxreg, 0, sizeof(trxreg));\n";
    os << "    bgcol = 0; gif_active = false; frame_count = 0;\n";
    os << "    LOGI(\"GS reset\");\n";
    os << "}\n";
    os << "\n";

    os << "void GS_State::write_priv(uint32_t addr, uint64_t val) {\n";
    os << "    uint32_t reg = addr & 0xFFFF;\n";
    os << "    switch (reg) {\n";
    os << "    case GS_PMODE:       pmode = (uint32_t)val; break;\n";
    os << "    case GS_FRAME1:\n";
    os << "        frame[0].fbp = (uint32_t)(val & 0x3FF);\n";
    os << "        frame[0].fbw = (uint32_t)((val >> 16) & 0x3F);\n";
    os << "        frame[0].psm = (uint32_t)((val >> 24) & 0x3F);\n";
    os << "        break;\n";
    os << "    case GS_FRAME2:\n";
    os << "        frame[1].fbp = (uint32_t)(val & 0x3FF);\n";
    os << "        frame[1].fbw = (uint32_t)((val >> 16) & 0x3F);\n";
    os << "        frame[1].psm = (uint32_t)((val >> 24) & 0x3F);\n";
    os << "        break;\n";
    os << "    case GS_ZBUF1:       zbuf[0] = (uint32_t)val; break;\n";
    os << "    case GS_ZBUF2:       zbuf[1] = (uint32_t)val; break;\n";
    os << "    case GS_XYOFFSET1:\n";
    os << "        xyoffset[0][0] = (int32_t)(val & 0xFFFF);\n";
    os << "        xyoffset[0][1] = (int32_t)((val >> 32) & 0xFFFF);\n";
    os << "        break;\n";
    os << "    case GS_XYOFFSET2:\n";
    os << "        xyoffset[1][0] = (int32_t)(val & 0xFFFF);\n";
    os << "        xyoffset[1][1] = (int32_t)((val >> 32) & 0xFFFF);\n";
    os << "        break;\n";
    os << "    case GS_SCISSOR1:\n";
    os << "        scissor[0][0] = (uint32_t)(val & 0x7FF);\n";
    os << "        scissor[0][1] = (uint32_t)((val >> 16) & 0x7FF);\n";
    os << "        scissor[0][2] = (uint32_t)((val >> 32) & 0x7FF);\n";
    os << "        scissor[0][3] = (uint32_t)((val >> 48) & 0x7FF);\n";
    os << "        break;\n";
    os << "    case GS_SCISSOR2:\n";
    os << "        scissor[1][0] = (uint32_t)(val & 0x7FF);\n";
    os << "        scissor[1][1] = (uint32_t)((val >> 16) & 0x7FF);\n";
    os << "        scissor[1][2] = (uint32_t)((val >> 32) & 0x7FF);\n";
    os << "        scissor[1][3] = (uint32_t)((val >> 48) & 0x7FF);\n";
    os << "        break;\n";
    os << "    case GS_ALPHA:       alpha = (uint32_t)val; break;\n";
    os << "    case GS_PRMODE:      prmode = (uint32_t)val; break;\n";
    os << "    case GS_PRMODECONT:  prmodecont = (uint32_t)val; break;\n";
    os << "    case GS_COLCLAMP:    colclamp = (uint32_t)val; break;\n";
    os << "    case GS_DTHE:        dthe = (uint32_t)val; break;\n";
    os << "    case GS_FOGCOL:      fogcol = (uint32_t)val; break;\n";
    os << "    case GS_FBA1:        fba[0] = (uint32_t)val; break;\n";
    os << "    case GS_FBA2:        fba[1] = (uint32_t)val; break;\n";
    os << "    case GS_BGCOLOR:     bgcol = (uint32_t)val; break;\n";
    os << "    case GS_TEX0_1:\n";
    os << "        tex[0].tbp0 = (uint32_t)(val & 0x3FFF);\n";
    os << "        tex[0].tbw = (uint32_t)((val >> 14) & 0x3F);\n";
    os << "        tex[0].psm = (uint32_t)((val >> 20) & 0x3F);\n";
    os << "        tex[0].tw = (uint32_t)((val >> 26) & 0xF);\n";
    os << "        tex[0].th = (uint32_t)((val >> 30) & 0xF);\n";
    os << "        tex[0].tcc = (uint32_t)((val >> 34) & 1);\n";
    os << "        tex[0].tfx = (uint32_t)((val >> 35) & 3);\n";
    os << "        tex[0].cld = (uint32_t)((val >> 51) & 7);\n";
    os << "        break;\n";
    os << "    case GS_TEX0_2:\n";
    os << "        tex[1].tbp0 = (uint32_t)(val & 0x3FFF);\n";
    os << "        tex[1].tbw = (uint32_t)((val >> 14) & 0x3F);\n";
    os << "        tex[1].psm = (uint32_t)((val >> 20) & 0x3F);\n";
    os << "        tex[1].tw = (uint32_t)((val >> 26) & 0xF);\n";
    os << "        tex[1].th = (uint32_t)((val >> 30) & 0xF);\n";
    os << "        tex[1].tcc = (uint32_t)((val >> 34) & 1);\n";
    os << "        tex[1].tfx = (uint32_t)((val >> 35) & 3);\n";
    os << "        tex[1].cld = (uint32_t)((val >> 51) & 7);\n";
    os << "        break;\n";
    os << "    case GS_TEXA:        texa = (uint32_t)val; break;\n";
    os << "    case GS_TEXCLUT:     texclut = (uint32_t)val; break;\n";
    os << "    case GS_TEXFLUSH:    LOGI(\"GS TEXFLUSH\"); break;\n";
    os << "    case GS_TRXDIR:      trxdir = (uint32_t)val; break;\n";
    os << "    case GS_TRXPOS:\n";
    os << "        trxpos[0] = (uint32_t)(val & 0x7FF);\n";
    os << "        trxpos[1] = (uint32_t)((val >> 16) & 0x7FF);\n";
    os << "        trxpos[2] = (uint32_t)((val >> 32) & 0x7FF);\n";
    os << "        trxpos[3] = (uint32_t)((val >> 48) & 0x7FF);\n";
    os << "        break;\n";
    os << "    case GS_TRXREG:\n";
    os << "        trxreg[0] = (uint32_t)(val & 0x7FF);\n";
    os << "        trxreg[1] = (uint32_t)((val >> 32) & 0x7FF);\n";
    os << "        break;\n";
    os << "    case GS_TRXKICK:\n";
    os << "        LOGI(\"GS TRXKICK: 0x%016llX\", (unsigned long long)val);\n";
    os << "        break;\n";
    os << "    case GS_DISPFB1:\n";
    os << "        dispfb[0].fbp = (uint32_t)(val & 0x1FF);\n";
    os << "        dispfb[0].fbw = (uint32_t)((val >> 9) & 0x3F);\n";
    os << "        dispfb[0].psm = (uint32_t)((val >> 15) & 0x3F);\n";
    os << "        break;\n";
    os << "    case GS_DISPFB2:\n";
    os << "        dispfb[1].fbp = (uint32_t)(val & 0x1FF);\n";
    os << "        dispfb[1].fbw = (uint32_t)((val >> 9) & 0x3F);\n";
    os << "        dispfb[1].psm = (uint32_t)((val >> 15) & 0x3F);\n";
    os << "        break;\n";
    os << "    default:\n";
    os << "        LOGW(\"GS write_priv: unhandled reg 0x%04X = 0x%016llX\", reg, (unsigned long long)val);\n";
    os << "        break;\n";
    os << "    }\n";
    os << "}\n";
    os << "\n";

    os << "uint64_t GS_State::read_priv(uint32_t addr) {\n";
    os << "    uint32_t reg = addr & 0xFFFF;\n";
    os << "    switch (reg) {\n";
    os << "    case GS_PMODE:  return pmode;\n";
    os << "    case GS_FRAME1: return (uint64_t)frame[0].fbp | ((uint64_t)frame[0].fbw << 16) | ((uint64_t)frame[0].psm << 24);\n";
    os << "    case GS_FRAME2: return (uint64_t)frame[1].fbp | ((uint64_t)frame[1].fbw << 16) | ((uint64_t)frame[1].psm << 24);\n";
    os << "    case GS_PRMODE: return prmode;\n";
    os << "    case GS_PRMODECONT: return prmodecont;\n";
    os << "    case GS_DISPFB1: return (uint64_t)dispfb[0].fbp | ((uint64_t)dispfb[0].fbw << 9) | ((uint64_t)dispfb[0].psm << 15);\n";
    os << "    case GS_DISPFB2: return (uint64_t)dispfb[1].fbp | ((uint64_t)dispfb[1].fbw << 9) | ((uint64_t)dispfb[1].psm << 15);\n";
    os << "    default:\n";
    os << "        LOGW(\"GS read_priv: unhandled reg 0x%04X\", reg);\n";
    os << "        return 0;\n";
    os << "    }\n";
    os << "}\n";
    os << "\n";

    os << "void GS_State::gif_transfer_tag(uint64_t tag_lo, uint64_t tag_hi) {\n";
    os << "    GIF_Tag tag;\n";
    os << "    memset(&tag, 0, sizeof(tag));\n";
    os << "    tag.nloop = (uint32_t)(tag_lo & 0x7FFF);\n";
    os << "    tag.eop   = (uint32_t)((tag_lo >> 15) & 1);\n";
    os << "    tag.pre   = (uint32_t)((tag_lo >> 46) & 1);\n";
    os << "    tag.prim  = (uint32_t)((tag_lo >> 47) & 0x7FF);\n";
    os << "    tag.flg   = (uint32_t)((tag_lo >> 58) & 3);\n";
    os << "    tag.nreg  = (uint32_t)((tag_lo >> 60) & 0xF);\n";
    os << "    if (tag.nreg == 0) tag.nreg = 4;\n";
    os << "    gif_active = (tag.nloop > 0);\n";
    os << "    LOGI(\"GIF tag: nloop=%d eop=%d flg=%d nreg=%d\", tag.nloop, tag.eop, tag.flg, tag.nreg);\n";
    os << "}\n";
    os << "\n";

    os << "void GS_State::gif_transfer_data(const uint64_t* data, int count) {\n";
    os << "    if (!gif_active || count <= 0) return;\n";
    os << "    for (int i = 0; i < count; i += 2) {\n";
    os << "        uint32_t addr = (uint32_t)(data[i]) & 0xFFFF;\n";
    os << "        uint64_t val = data[i + 1];\n";
    os << "        write_priv(addr, val);\n";
    os << "    }\n";
    os << "}\n";
    os << "\n";

    os << "void GS_State::upload_texture(uint32_t sbp, uint32_t sbw, uint32_t spsm,\n";
    os << "                              uint32_t dbp, uint32_t dbw, uint32_t dpsm,\n";
    os << "                              uint32_t src_x, uint32_t src_y,\n";
    os << "                              uint32_t dst_x, uint32_t dst_y,\n";
    os << "                              uint32_t width, uint32_t height) {\n";
    os << "    if (dbp + dbw * height * 4 > VRAM_SIZE) {\n";
    os << "        LOGE(\"GS upload_texture: dest out of VRAM bounds\");\n";
    os << "        return;\n";
    os << "    }\n";
    os << "    LOGI(\"GS upload_texture: src=(%u,%u) dst=(%u,%u) %ux%u psm=%u->%u\",\n";
    os << "         src_x, src_y, dst_x, dst_y, width, height, spsm, dpsm);\n";
    os << "    if (spsm == 0 && dpsm == 0) {\n";
    os << "        for (uint32_t y = 0; y < height; y++) {\n";
    os << "            uint32_t* dst = (uint32_t*)vram;\n";
    os << "            uint32_t* src = (uint32_t*)vram;\n";
    os << "            uint32_t di = (dst_y + y) * dbw + dst_x;\n";
    os << "            uint32_t si = (src_y + y) * sbw + src_x;\n";
    os << "            if (di + width <= VRAM_SIZE / 4 && si + width <= VRAM_SIZE / 4)\n";
    os << "                memcpy(&dst[di], &src[si], width * 4);\n";
    os << "        }\n";
    os << "    }\n";
    os << "}\n";

    return os.str();
}

// ============================================================================
// DMA Module
// ============================================================================

HWModule HW_ModuleGen::generate_dma_module(const ELF_Analyzer& analyzer) {
    HWModule mod;
    mod.name = "dma";
    mod.header_code = generate_dma_header();
    mod.source_code = generate_dma_source();
    return mod;
}

std::string HW_ModuleGen::generate_dma_header() {
    std::ostringstream os;

    os << "#pragma once\n";
    os << "#include <cstdint>\n";
    os << "#include <cstring>\n";
    os << "#include <functional>\n";
    os << "#include <vector>\n";
    os << "\n";
    os << "// DMA controller - self-contained, no emulator dependencies\n";
    os << "// Generated by HW_ModuleGen for PS2-Recompiler AOT pipeline\n";
    os << "\n";

    os << "enum DMA_Channel : int {\n";
    os << "    DMA_VIF0=0, DMA_VIF1=1, DMA_GIF=2,\n";
    os << "    DMA_FROM_IPU=3, DMA_TO_IPU=4,\n";
    os << "    DMA_SIF0=5, DMA_SIF1=6, DMA_SIF2=7,\n";
    os << "    DMA_FROM_SPR=8, DMA_TO_SPR=9,\n";
    os << "    DMA_CHANNEL_COUNT = 10\n";
    os << "};\n";
    os << "\n";

    os << "static constexpr uint32_t DMA_CH_BASE   = 0x10008000;\n";
    os << "static constexpr uint32_t DMA_CH_STRIDE = 0x10;\n";
    os << "static constexpr uint32_t DMA_DPCR      = 0x1000E000;\n";
    os << "static constexpr uint32_t DMA_DPCR2     = 0x1000F000;\n";
    os << "static constexpr uint32_t DMA_STAT      = 0x1000E010;\n";
    os << "static constexpr uint32_t DMA_STAT2     = 0x1000F020;\n";
    os << "\n";

    os << "struct DMA_Reg {\n";
    os << "    uint32_t madr, qwc, tag, chcr;\n";
    os << "    bool direction()   const { return (chcr & 1) != 0; }\n";
    os << "    bool mode_normal() const { return ((chcr >> 2) & 3) == 0; }\n";
    os << "    bool mode_chain()  const { return ((chcr >> 2) & 3) == 1; }\n";
    os << "    bool mode_inter()  const { return ((chcr >> 2) & 3) == 2; }\n";
    os << "    bool started()     const { return (chcr & (1u << 24)) != 0; }\n";
    os << "    bool tag_irq()     const { return (chcr & (1u << 31)) != 0; }\n";
    os << "    void reset() { madr = 0; qwc = 0; tag = 0; chcr = 0; }\n";
    os << "};\n";
    os << "\n";

    os << "struct DMA_State {\n";
    os << "    DMA_Reg channels[DMA_CHANNEL_COUNT];\n";
    os << "    uint32_t dpcr, dpcr2, dicr, dicr2;\n";
    os << "    std::function<void(int ch, const uint32_t* src, uint32_t words)> on_read;\n";
    os << "    std::function<void(int ch, uint32_t* dst, uint32_t words)> on_write;\n";
    os << "    void reset();\n";
    os << "    void write_register(uint32_t addr, uint32_t val);\n";
    os << "    uint32_t read_register(uint32_t addr);\n";
    os << "    void start_transfer(int ch);\n";
    os << "    void execute_normal(int ch);\n";
    os << "    void execute_chain(int ch);\n";
    os << "    void execute_interleave(int ch);\n";
    os << "    void update_interrupts();\n";
    os << "};\n";

    return os.str();
}

std::string HW_ModuleGen::generate_dma_source() {
    std::ostringstream os;

    os << "#include \"dma_controller.h\"\n";
    os << "#include <android/log.h>\n";
    os << "#include <cstring>\n";
    os << "\n";
    os << "#define LOG_TAG \"DMA\"\n";
    os << "#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)\n";
    os << "#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)\n";
    os << "#define LOGW(...) __android_log_print(ANDROID_LOG_WARN, LOG_TAG, __VA_ARGS__)\n";
    os << "\n";

    os << "void DMA_State::reset() {\n";
    os << "    for (int i = 0; i < DMA_CHANNEL_COUNT; i++) channels[i].reset();\n";
    os << "    dpcr = 0x00000765;\n";
    os << "    dpcr2 = 0x00000765;\n";
    os << "    dicr = 0;\n";
    os << "    dicr2 = 0;\n";
    os << "    LOGI(\"DMA reset\");\n";
    os << "}\n";
    os << "\n";

    os << "void DMA_State::write_register(uint32_t addr, uint32_t val) {\n";
    os << "    if (addr >= DMA_CH_BASE && addr < DMA_CH_BASE + DMA_CHANNEL_COUNT * DMA_CH_STRIDE) {\n";
    os << "        int ch = (addr - DMA_CH_BASE) / DMA_CH_STRIDE;\n";
    os << "        int off = (addr - DMA_CH_BASE) % DMA_CH_STRIDE;\n";
    os << "        switch (off) {\n";
    os << "        case 0x0: channels[ch].madr = val; break;\n";
    os << "        case 0x4: channels[ch].qwc = val; break;\n";
    os << "        case 0x8: channels[ch].tag = val; break;\n";
    os << "        case 0xC:\n";
    os << "            channels[ch].chcr = val;\n";
    os << "            if (channels[ch].started()) start_transfer(ch);\n";
    os << "            break;\n";
    os << "        }\n";
    os << "        return;\n";
    os << "    }\n";
    os << "    if (addr == DMA_DPCR)  { dpcr = val;  return; }\n";
    os << "    if (addr == DMA_DPCR2) { dpcr2 = val; return; }\n";
    os << "    if (addr == DMA_STAT)  { dicr &= ~val; update_interrupts(); return; }\n";
    os << "    if (addr == DMA_STAT2) { dicr2 &= ~val; update_interrupts(); return; }\n";
    os << "    LOGW(\"DMA write_register: unmapped 0x%08X = 0x%08X\", addr, val);\n";
    os << "}\n";
    os << "\n";

    os << "uint32_t DMA_State::read_register(uint32_t addr) {\n";
    os << "    if (addr >= DMA_CH_BASE && addr < DMA_CH_BASE + DMA_CHANNEL_COUNT * DMA_CH_STRIDE) {\n";
    os << "        int ch = (addr - DMA_CH_BASE) / DMA_CH_STRIDE;\n";
    os << "        int off = (addr - DMA_CH_BASE) % DMA_CH_STRIDE;\n";
    os << "        switch (off) {\n";
    os << "        case 0x0: return channels[ch].madr;\n";
    os << "        case 0x4: return channels[ch].qwc;\n";
    os << "        case 0x8: return channels[ch].tag;\n";
    os << "        case 0xC: return channels[ch].chcr;\n";
    os << "        }\n";
    os << "    }\n";
    os << "    if (addr == DMA_DPCR)  return dpcr;\n";
    os << "    if (addr == DMA_DPCR2) return dpcr2;\n";
    os << "    if (addr == DMA_STAT)  return dicr;\n";
    os << "    if (addr == DMA_STAT2) return dicr2;\n";
    os << "    LOGW(\"DMA read_register: unmapped 0x%08X\", addr);\n";
    os << "    return 0;\n";
    os << "}\n";
    os << "\n";

    os << "void DMA_State::start_transfer(int ch) {\n";
    os << "    if (ch < 0 || ch >= DMA_CHANNEL_COUNT) return;\n";
    os << "    DMA_Reg& reg = channels[ch];\n";
    os << "    LOGI(\"DMA start: ch=%d madr=0x%08X qwc=%d mode=%s\",\n";
    os << "         ch, reg.madr, reg.qwc,\n";
    os << "         reg.mode_chain() ? \"chain\" : reg.mode_inter() ? \"interleave\" : \"normal\");\n";
    os << "    if (reg.mode_chain()) execute_chain(ch);\n";
    os << "    else if (reg.mode_inter()) execute_interleave(ch);\n";
    os << "    else execute_normal(ch);\n";
    os << "    reg.chcr &= ~(1u << 24);\n";
    os << "    update_interrupts();\n";
    os << "}\n";
    os << "\n";

    os << "void DMA_State::execute_normal(int ch) {\n";
    os << "    DMA_Reg& reg = channels[ch];\n";
    os << "    if (reg.qwc == 0) return;\n";
    os << "    uint32_t words = reg.qwc * 4;\n";
    os << "    if (on_read && reg.direction()) {\n";
    os << "        std::vector<uint32_t> buf(words);\n";
    os << "        on_read(ch, buf.data(), words);\n";
    os << "    } else if (on_write && !reg.direction()) {\n";
    os << "        std::vector<uint32_t> buf(words);\n";
    os << "        on_write(ch, buf.data(), words);\n";
    os << "    }\n";
    os << "    reg.madr += words * 4;\n";
    os << "    reg.qwc = 0;\n";
    os << "    LOGI(\"DMA normal: ch=%d transferred %u words\", ch, words);\n";
    os << "}\n";
    os << "\n";

    os << "void DMA_State::execute_chain(int ch) {\n";
    os << "    DMA_Reg& reg = channels[ch];\n";
    os << "    while (reg.madr != 0 && reg.qwc != 0) {\n";
    os << "        uint32_t words = reg.qwc * 4;\n";
    os << "        if (on_read && reg.direction()) {\n";
    os << "            std::vector<uint32_t> buf(words);\n";
    os << "            on_read(ch, buf.data(), words);\n";
    os << "        }\n";
    os << "        reg.madr += words * 4;\n";
    os << "        if (on_read) {\n";
    os << "            std::vector<uint32_t> tag_buf(4);\n";
    os << "            on_read(ch, tag_buf.data(), 4);\n";
    os << "            reg.tag = tag_buf[0];\n";
    os << "            uint32_t next_addr = tag_buf[1] & 0x1FFFFFFF;\n";
    os << "            uint32_t next_qwc  = tag_buf[2] & 0xFFFF;\n";
    os << "            LOGI(\"DMA chain tag: addr=0x%08X qwc=%d\", next_addr, next_qwc);\n";
    os << "            if (next_qwc == 0 && next_addr == 0) break;\n";
    os << "            reg.madr = next_addr;\n";
    os << "            reg.qwc = next_qwc;\n";
    os << "            if (reg.tag_irq()) dicr |= (1u << (24 + ch));\n";
    os << "        } else {\n";
    os << "            break;\n";
    os << "        }\n";
    os << "    }\n";
    os << "    reg.qwc = 0;\n";
    os << "    LOGI(\"DMA chain: ch=%d completed\", ch);\n";
    os << "}\n";
    os << "\n";

    os << "void DMA_State::execute_interleave(int ch) {\n";
    os << "    DMA_Reg& reg = channels[ch];\n";
    os << "    if (reg.qwc == 0) return;\n";
    os << "    uint32_t words = reg.qwc * 4;\n";
    os << "    if (on_read && reg.direction()) {\n";
    os << "        std::vector<uint32_t> buf(words);\n";
    os << "        on_read(ch, buf.data(), words);\n";
    os << "    } else if (on_write && !reg.direction()) {\n";
    os << "        std::vector<uint32_t> buf(words);\n";
    os << "        on_write(ch, buf.data(), words);\n";
    os << "    }\n";
    os << "    reg.madr += words * 4;\n";
    os << "    reg.qwc = 0;\n";
    os << "    LOGI(\"DMA interleave: ch=%d transferred %u words\", ch, words);\n";
    os << "}\n";
    os << "\n";

    os << "void DMA_State::update_interrupts() {\n";
    os << "    uint32_t status = (dicr >> 24) & 0x7F;\n";
    os << "    uint32_t enable = (dicr >> 16) & 0x7F;\n";
    os << "    uint32_t force  = dicr & 0x7F;\n";
    os << "    uint32_t irq = (status | force) & enable;\n";
    os << "    if (irq) dicr |= (1u << 31);\n";
    os << "    else dicr &= ~(1u << 31);\n";
    os << "    LOGI(\"DMA update_interrupts: DICR=0x%08X irq=0x%02X\", dicr, irq);\n";
    os << "}\n";

    return os.str();
}

// ============================================================================
// VU Module
// ============================================================================

HWModule HW_ModuleGen::generate_vu_module(const ELF_Analyzer& analyzer) {
    HWModule mod;
    mod.name = "vu";
    mod.header_code = generate_vu_header();
    mod.source_code = generate_vu_source();
    return mod;
}

std::string HW_ModuleGen::generate_vu_header() {
    std::ostringstream os;

    os << "#pragma once\n";
    os << "#include <cstdint>\n";
    os << "#include <cstring>\n";
    os << "#include <array>\n";
    os << "\n";
    os << "// VU processor - self-contained, no emulator dependencies\n";
    os << "// Generated by HW_ModuleGen for PS2-Recompiler AOT pipeline\n";
    os << "\n";
    os << "static constexpr int VU_MICRO_MEM_MAX = 16 * 1024;\n";
    os << "static constexpr int VU_DATA_MEM_MAX  = 16 * 1024;\n";
    os << "static constexpr int VU_VF_COUNT      = 32;\n";
    os << "static constexpr int VU_VI_COUNT      = 16;\n";
    os << "\n";

    os << "struct VU_VF {\n";
    os << "    float f[4];\n";
    os << "    void load(const float* src) { memcpy(f, src, 16); }\n";
    os << "    void store(float* dst) const { memcpy(dst, f, 16); }\n";
    os << "    void reset() { memset(f, 0, sizeof(f)); }\n";
    os << "    float x() const { return f[0]; }\n";
    os << "    float y() const { return f[1]; }\n";
    os << "    float z() const { return f[2]; }\n";
    os << "    float w() const { return f[3]; }\n";
    os << "    void set_x(float v) { f[0] = v; }\n";
    os << "    void set_y(float v) { f[1] = v; }\n";
    os << "    void set_z(float v) { f[2] = v; }\n";
    os << "    void set_w(float v) { f[3] = v; }\n";
    os << "};\n";
    os << "\n";

    os << "struct VU_Flags {\n";
    os << "    uint16_t mac;\n";
    os << "    uint16_t status;\n";
    os << "    uint32_t clip;\n";
    os << "    void reset() { mac = 0; status = 0; clip = 0; }\n";
    os << "    void update_clip(float x, float y, float z, float w) {\n";
    os << "        clip <<= 4;\n";
    os << "        clip |= (x < 0 ? 8 : 0) | (x > w ? 4 : 0) |\n";
    os << "                (y < 0 ? 2 : 0) | (y > w ? 1 : 0);\n";
    os << "    }\n";
    os << "};\n";
    os << "\n";

    os << "struct VU_State {\n";
    os << "    uint8_t micro_mem[VU_MICRO_MEM_MAX];\n";
    os << "    uint8_t data_mem[VU_DATA_MEM_MAX];\n";
    os << "    VU_VF vf[VU_VF_COUNT];\n";
    os << "    uint16_t vi[VU_VI_COUNT];\n";
    os << "    VU_Flags flags;\n";
    os << "    uint32_t pc, pipeline_pc;\n";
    os << "    bool running, finished;\n";
    os << "    float i_top, i_bottom, q, p;\n";
    os << "    uint32_t revision, id;\n";
    os << "    uint64_t cycle_count;\n";
    os << "    void reset();\n";
    os << "    void reset_flags();\n";
    os << "    void load_program(const uint32_t* data, uint32_t word_count);\n";
    os << "    void load_data(uint32_t addr, const uint32_t* data, uint32_t word_count);\n";
    os << "    void store_data(uint32_t addr, uint32_t* data, uint32_t word_count);\n";
    os << "    uint32_t read_reg_vi(int reg) const;\n";
    os << "    void     write_reg_vi(int reg, uint16_t val);\n";
    os << "    VU_VF    read_reg_vf(int reg) const;\n";
    os << "    void     write_reg_vf(int reg, const VU_VF& val);\n";
    os << "    void cop2_madd(int vd, int vs, int vt);\n";
    os << "    void cop2_msub(int vd, int vs, int vt);\n";
    os << "    void cop2_mul(int vd, int vs, int vt);\n";
    os << "    void cop2_maddi(int vd, int vs, int it);\n";
    os << "    void cop2_msubi(int vd, int vs, int it);\n";
    os << "    void cop2_muli(int vd, int vs, int it);\n";
    os << "    void cop2_add(int vd, int vs, int vt);\n";
    os << "    void cop2_sub(int vd, int vs, int vt);\n";
    os << "    void cop2_addi(int vd, int vs, int it);\n";
    os << "    void cop2_subi(int vd, int vs, int it);\n";
    os << "    void cop2_move(int vd, int vs);\n";
    os << "    void cop2_lq(int vd, uint16_t addr);\n";
    os << "    void cop2_sq(int vs, uint16_t addr);\n";
    os << "    void cop2_wait();\n";
    os << "    void cop2_xgkick();\n";
    os << "};\n";

    return os.str();
}

std::string HW_ModuleGen::generate_vu_source() {
    std::ostringstream os;

    os << "#include \"vu_processor.h\"\n";
    os << "#include <android/log.h>\n";
    os << "#include <cstring>\n";
    os << "#include <cmath>\n";
    os << "\n";
    os << "#define LOG_TAG \"VU\"\n";
    os << "#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)\n";
    os << "#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)\n";
    os << "#define LOGW(...) __android_log_print(ANDROID_LOG_WARN, LOG_TAG, __VA_ARGS__)\n";
    os << "\n";

    os << "void VU_State::reset() {\n";
    os << "    memset(micro_mem, 0, sizeof(micro_mem));\n";
    os << "    memset(data_mem, 0, sizeof(data_mem));\n";
    os << "    for (int i = 0; i < VU_VF_COUNT; i++) vf[i].reset();\n";
    os << "    memset(vi, 0, sizeof(vi));\n";
    os << "    flags.reset();\n";
    os << "    pc = 0; pipeline_pc = 0;\n";
    os << "    running = false; finished = false;\n";
    os << "    i_top = 0.0f; i_bottom = 0.0f; q = 0.0f; p = 0.0f;\n";
    os << "    revision = 0x00068401; id = 0; cycle_count = 0;\n";
    os << "    LOGI(\"VU reset\");\n";
    os << "}\n";
    os << "\n";
    os << "void VU_State::reset_flags() { flags.reset(); }\n";
    os << "\n";

    os << "void VU_State::load_program(const uint32_t* data, uint32_t word_count) {\n";
    os << "    uint32_t bytes = word_count * 4;\n";
    os << "    if (bytes > VU_MICRO_MEM_MAX) bytes = VU_MICRO_MEM_MAX;\n";
    os << "    memcpy(micro_mem, data, bytes);\n";
    os << "    pc = 0;\n";
    os << "    LOGI(\"VU program loaded: %u words\", word_count);\n";
    os << "}\n";
    os << "\n";
    os << "void VU_State::load_data(uint32_t addr, const uint32_t* data, uint32_t word_count) {\n";
    os << "    addr &= (VU_DATA_MEM_MAX - 1);\n";
    os << "    uint32_t bytes = word_count * 4;\n";
    os << "    if (addr + bytes > VU_DATA_MEM_MAX) bytes = VU_DATA_MEM_MAX - addr;\n";
    os << "    memcpy(data_mem + addr, data, bytes);\n";
    os << "}\n";
    os << "\n";
    os << "void VU_State::store_data(uint32_t addr, uint32_t* data, uint32_t word_count) {\n";
    os << "    addr &= (VU_DATA_MEM_MAX - 1);\n";
    os << "    uint32_t bytes = word_count * 4;\n";
    os << "    if (addr + bytes > VU_DATA_MEM_MAX) bytes = VU_DATA_MEM_MAX - addr;\n";
    os << "    memcpy(data, data_mem + addr, bytes);\n";
    os << "}\n";
    os << "\n";

    os << "uint32_t VU_State::read_reg_vi(int reg) const {\n";
    os << "    return (reg > 0 && reg < VU_VI_COUNT) ? vi[reg] : 0;\n";
    os << "}\n";
    os << "\n";
    os << "void VU_State::write_reg_vi(int reg, uint16_t val) {\n";
    os << "    if (reg > 0 && reg < VU_VI_COUNT) vi[reg] = val;\n";
    os << "}\n";
    os << "\n";
    os << "VU_VF VU_State::read_reg_vf(int reg) const {\n";
    os << "    if (reg >= 0 && reg < VU_VF_COUNT) return vf[reg];\n";
    os << "    VU_VF zero; zero.reset(); return zero;\n";
    os << "}\n";
    os << "\n";
    os << "void VU_State::write_reg_vf(int reg, const VU_VF& val) {\n";
    os << "    if (reg >= 1 && reg < VU_VF_COUNT) vf[reg] = val;\n";
    os << "}\n";
    os << "\n";

    os << "void VU_State::cop2_madd(int vd, int vs, int vt) {\n";
    os << "    for (int i = 0; i < 4; i++)\n";
    os << "        vf[vd].f[i] = vf[vs].f[i] * vf[vt].f[i] + p;\n";
    os << "    flags.mac = 0;\n";
    os << "    for (int i = 0; i < 4; i++) {\n";
    os << "        if (vf[vd].f[i] == 0.0f) flags.mac |= (1u << (i + 0));\n";
    os << "        if (vf[vd].f[i] <  0.0f) flags.mac |= (1u << (i + 4));\n";
    os << "    }\n";
    os << "    LOGI(\"VU COP2 MADD vd=%d vs=%d vt=%d\", vd, vs, vt);\n";
    os << "}\n";
    os << "\n";
    os << "void VU_State::cop2_msub(int vd, int vs, int vt) {\n";
    os << "    for (int i = 0; i < 4; i++)\n";
    os << "        vf[vd].f[i] = vf[vs].f[i] * vf[vt].f[i] - p;\n";
    os << "    flags.mac = 0;\n";
    os << "    for (int i = 0; i < 4; i++) {\n";
    os << "        if (vf[vd].f[i] == 0.0f) flags.mac |= (1u << (i + 0));\n";
    os << "        if (vf[vd].f[i] <  0.0f) flags.mac |= (1u << (i + 4));\n";
    os << "    }\n";
    os << "    LOGI(\"VU COP2 MSUB vd=%d vs=%d vt=%d\", vd, vs, vt);\n";
    os << "}\n";
    os << "\n";
    os << "void VU_State::cop2_mul(int vd, int vs, int vt) {\n";
    os << "    for (int i = 0; i < 4; i++)\n";
    os << "        vf[vd].f[i] = vf[vs].f[i] * vf[vt].f[i];\n";
    os << "    flags.mac = 0;\n";
    os << "    for (int i = 0; i < 4; i++) {\n";
    os << "        if (vf[vd].f[i] == 0.0f) flags.mac |= (1u << (i + 0));\n";
    os << "        if (vf[vd].f[i] <  0.0f) flags.mac |= (1u << (i + 4));\n";
    os << "    }\n";
    os << "}\n";
    os << "\n";
    os << "void VU_State::cop2_maddi(int vd, int vs, int it) {\n";
    os << "    float vi_val = (float)(int16_t)vi[it];\n";
    os << "    for (int i = 0; i < 4; i++)\n";
    os << "        vf[vd].f[i] = vf[vs].f[i] * vi_val + p;\n";
    os << "    LOGI(\"VU COP2 MADDI vd=%d vs=%d it=%d\", vd, vs, it);\n";
    os << "}\n";
    os << "\n";
    os << "void VU_State::cop2_msubi(int vd, int vs, int it) {\n";
    os << "    float vi_val = (float)(int16_t)vi[it];\n";
    os << "    for (int i = 0; i < 4; i++)\n";
    os << "        vf[vd].f[i] = vf[vs].f[i] * vi_val - p;\n";
    os << "    LOGI(\"VU COP2 MSUBI vd=%d vs=%d it=%d\", vd, vs, it);\n";
    os << "}\n";
    os << "\n";
    os << "void VU_State::cop2_muli(int vd, int vs, int it) {\n";
    os << "    float vi_val = (float)(int16_t)vi[it];\n";
    os << "    for (int i = 0; i < 4; i++)\n";
    os << "        vf[vd].f[i] = vf[vs].f[i] * vi_val;\n";
    os << "}\n";
    os << "\n";
    os << "void VU_State::cop2_add(int vd, int vs, int vt) {\n";
    os << "    for (int i = 0; i < 4; i++)\n";
    os << "        vf[vd].f[i] = vf[vs].f[i] + vf[vt].f[i];\n";
    os << "}\n";
    os << "\n";
    os << "void VU_State::cop2_sub(int vd, int vs, int vt) {\n";
    os << "    for (int i = 0; i < 4; i++)\n";
    os << "        vf[vd].f[i] = vf[vs].f[i] - vf[vt].f[i];\n";
    os << "}\n";
    os << "\n";
    os << "void VU_State::cop2_addi(int vd, int vs, int it) {\n";
    os << "    float vi_val = (float)(int16_t)vi[it];\n";
    os << "    for (int i = 0; i < 4; i++)\n";
    os << "        vf[vd].f[i] = vf[vs].f[i] + vi_val;\n";
    os << "}\n";
    os << "\n";
    os << "void VU_State::cop2_subi(int vd, int vs, int it) {\n";
    os << "    float vi_val = (float)(int16_t)vi[it];\n";
    os << "    for (int i = 0; i < 4; i++)\n";
    os << "        vf[vd].f[i] = vf[vs].f[i] - vi_val;\n";
    os << "}\n";
    os << "\n";
    os << "void VU_State::cop2_move(int vd, int vs) { vf[vd] = vf[vs]; }\n";
    os << "\n";

    os << "void VU_State::cop2_lq(int vd, uint16_t addr) {\n";
    os << "    addr &= (VU_DATA_MEM_MAX - 16);\n";
    os << "    memcpy(vf[vd].f, data_mem + addr, 16);\n";
    os << "    LOGI(\"VU COP2 LQ vd=%d addr=0x%04X\", vd, addr);\n";
    os << "}\n";
    os << "\n";
    os << "void VU_State::cop2_sq(int vs, uint16_t addr) {\n";
    os << "    addr &= (VU_DATA_MEM_MAX - 16);\n";
    os << "    memcpy(data_mem + addr, vf[vs].f, 16);\n";
    os << "    LOGI(\"VU COP2 SQ vs=%d addr=0x%04X\", vs, addr);\n";
    os << "}\n";
    os << "\n";
    os << "void VU_State::cop2_wait() { LOGI(\"VU COP2 WAIT\"); }\n";
    os << "void VU_State::cop2_xgkick() { LOGI(\"VU COP2 XGKICK (stub)\"); }\n";

    return os.str();
}
